index:
    path: /
    controller: App\Controller\Dashboard\DashboardController::dashboard

dashboard:
    path: /{_locale}/dashboard
    controller: App\Controller\Dashboard\DashboardController::dashboard

glossary:
    path: /{_locale}/glossary
    controller: App\Controller\Glossary\GlossaryEntryController::createNewEntry

find_entry:
    path: /{_locale}/find_entry
    controller: App\Controller\Glossary\FindEntryController::findEntry

edit:
    path: /{_locale}/edit/{id}
    controller: App\Controller\Glossary\GlossaryEntryController::editEntry

delete:
    path: /{_locale}/delete/{id}
    controller: App\Controller\Glossary\GlossaryEntryController::deleteEntry

list:
    path: /{_locale}/list
    controller: App\Controller\Glossary\ListController::list

xml_export:
    path: /{_locale}/xml_export
    controller: App\Controller\Exporter\ExportController::exportXml

csv_export:
    path: /{_locale}/csv_export
    controller: App\Controller\Exporter\ExportController::exportCsv

export:
    path: /{_locale}/export
    controller: App\Controller\Exporter\ExportController::export
