index:
    path: /
    controller: App\Controller\Dashboard\DashboardController::dashboard

locale_dashboard:
    path: /{_locale}/dashboard
    controller: App\Controller\Dashboard\DashboardController::dashboard

dashboard:
    path: /{_locale}/dashboard
    controller: App\Controller\Dashboard\DashboardController::dashboard

glossary:
    path: /{_locale}/glossary
    controller: App\Controller\Glossary\GlossaryEntryController::createNewEntry

#   export:
#      path: /export
#      controller: App\Controller\Glossary\ExportController::export

#   import:
#       path: /import
#       controller: App\Controller\Glossary\ImportController::import

find_entry:
    path: /{_locale}/find_entry
    controller: App\Controller\Glossary\FindEntryController::findEntry

edit:
    path: /{_locale}/edit/{id}
    controller: App\Controller\Glossary\GlossaryEntryController::editEntry

delete:
    path: /{_locale}/delete/{id}
    controller: App\Controller\Glossary\GlossaryEntryController::deleteEntry

list:
    path: /{_locale}/list
    controller: App\Controller\Glossary\ListController::list
